openapi: 3.0.0
info:
  title: 'List cars'
  version: '1.0'
servers:
  -
    url: recrutei.test
paths:
  /register:
    post:
      description: 'Register a user'
      operationId: 'App\Http\Controllers\Api\AuthController::register'
      parameters:
        -
          name: body
          in: query
          required: true
          schema:
            properties:
              email:
                type: string
              name:
                type: string
              password:
                type: integer
            type: object
      responses:
        '201':
          description: Created
        '422':
          description: 'Unprocessable Entity'
  /login:
    post:
      description: Login
      operationId: 'App\Http\Controllers\Api\AuthController::login'
      parameters:
        -
          name: body
          in: query
          required: true
          schema:
            properties:
              email:
                type: string
              password:
                type: integer
            type: object
      responses:
        '201':
          description: Created
        '422':
          description: 'Unprocessable Entity'
  /users:
    put:
      description: 'Update a user with the data informed'
      operationId: 'App\Http\Controllers\Api\AuthController::update'
      parameters:
        -
          name: body
          in: query
          required: true
          schema:
            properties:
              email:
                type: string
              name:
                type: string
              password:
                type: integer
            type: object
      responses:
        '200':
          description: OK
        '422':
          description: 'Unprocessable Entity'
        '401':
          description: Unauthorized
  '/cars/{id}':
    get:
      description: 'Lists the cars created, by the filters'
      operationId: 'App\Http\Controllers\Api\CarController::show'
      parameters:
        -
          name: id
          in: path
          description: 'Id of the car'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    put:
      description: 'Update a car with the data informed'
      operationId: 'App\Http\Controllers\Api\CarController::update'
      parameters:
        -
          name: id
          in: path
          description: 'Id of the car'
          required: true
          schema:
            type: integer
        -
          name: body
          in: query
          required: true
          schema:
            properties:
              model:
                type: string
              category:
                type: string
              ports:
                type: integer
              board:
                type: string
              type_vehicle:
                type: string
              year:
                type: string
              fuel:
                type: string
              mileage:
                type: string
              exchange:
                type: string
              direction:
                type: string
              color:
                type: string
              options:
                type: string
            type: object
      responses:
        '200':
          description: OK
        '422':
          description: 'Unprocessable Entity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      description: 'Delete a car'
      operationId: 'App\Http\Controllers\Api\CarController::destroy'
      parameters:
        -
          name: id
          in: path
          description: 'Id of the record'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '422':
          description: 'Unprocessable Entity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /cars:
    get:
      description: 'Lists all the cars created'
      operationId: 'App\Http\Controllers\Api\CarController::show'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      description: 'Save a car with the data informed'
      operationId: 'App\Http\Controllers\Api\CarController::store'
      parameters:
        -
          name: body
          in: query
          required: true
          schema:
            properties:
              model:
                type: string
              category:
                type: string
              ports:
                type: integer
              board:
                type: string
              type_vehicle:
                type: string
              year:
                type: string
              fuel:
                type: string
              mileage:
                type: string
              exchange:
                type: string
              direction:
                type: string
              color:
                type: string
              options:
                type: string
            type: object
      responses:
        '201':
          description: Created
        '422':
          description: 'Unprocessable Entity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /roles:
    get:
      description: 'Lists the roles created'
      operationId: 'App\Http\Controllers\Api\RoleController::index'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      description: 'Save a role with the data informed'
      operationId: 'App\Http\Controllers\Api\RoleController::store'
      parameters:
        -
          name: body
          in: query
          required: true
          schema:
            properties:
              user_id:
                type: integer
              role:
                type: string
            type: object
      responses:
        '201':
          description: Created
        '422':
          description: 'Unprocessable Entity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/roles/{id}/{role}':
    get:
      description: 'Lists the roles created, by the filters'
      operationId: 'App\Http\Controllers\Api\RoleController::show'
      parameters:
        -
          name: id
          in: path
          description: 'Id of the role'
          required: true
          schema:
            type: integer
        -
          name: role
          in: path
          description: 'Name of the role'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      description: 'Delete a role'
      operationId: 'App\Http\Controllers\Api\RoleController::destroy'
      parameters:
        -
          name: id
          in: path
          description: 'Id of the record'
          required: true
          schema:
            type: integer
        -
          name: role
          in: path
          description: 'Role of the user'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '422':
          description: 'Unprocessable Entity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
